# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Jollybus
tagline:             'A Jekyll theme'
description:         'Development, English, and Living'
url:                 http://www.jollybus.kr
baseurl:             ''
paginate:            5
markdown: kramdown
gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

# About/contact
author:
  name:              Hoyeong Heo
  url:               https://kr.linkedin.com/in/hotohoto82
  # email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
