---
title: Jollybus
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
tagline: Development and Living
description: A blog about the software development and my everyday life.
url: https://hotohoto.github.com
baseurl: ''
markdown: kramdown
gems:
- jekyll-seo-tag
- jekyll-sitemap
author:
  name: Hoyeong Heo
  url: https://kr.linkedin.com/in/hotohoto82
  email: hotohoto82@gmail.com
version: 1.0.0
